/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 31
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  sym_number = 2,
  sym_string = 3,
  anon_sym_TRUE = 4,
  anon_sym_FALSE = 5,
  sym_identifier = 6,
  anon_sym_POUNDNULL_BANG = 7,
  anon_sym_POUNDDIV_SLASH0_BANG = 8,
  anon_sym_POUNDVALUE_BANG = 9,
  anon_sym_POUNDREF_BANG = 10,
  anon_sym_POUNDNAME_QMARK = 11,
  anon_sym_POUNDNUM_BANG = 12,
  anon_sym_POUNDN_SLASHA = 13,
  anon_sym_POUNDERROR_BANG = 14,
  anon_sym_LBRACE = 15,
  anon_sym_COMMA = 16,
  anon_sym_SEMI = 17,
  anon_sym_RBRACE = 18,
  anon_sym_BANG = 19,
  aux_sym_cell_reference_token1 = 20,
  anon_sym_PERCENT = 21,
  anon_sym_PLUS = 22,
  anon_sym_DASH = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  anon_sym_CARET = 26,
  anon_sym_AMP = 27,
  anon_sym_GT = 28,
  anon_sym_LT = 29,
  anon_sym_LT_EQ = 30,
  anon_sym_GT_EQ = 31,
  anon_sym_COLON = 32,
  sym_open_paren = 33,
  sym_close_paren = 34,
  sym_source_file = 35,
  sym_boolean = 36,
  sym_error_literal = 37,
  sym_array_literal = 38,
  sym_cell_reference = 39,
  sym_operator_expression = 40,
  sym_unary_operator = 41,
  sym_binary_operator = 42,
  sym_expression = 43,
  sym_parenthesized_expression = 44,
  sym_function_call = 45,
  aux_sym_array_literal_repeat1 = 46,
  aux_sym_array_literal_repeat2 = 47,
  aux_sym_function_call_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_TRUE] = "TRUE",
  [anon_sym_FALSE] = "FALSE",
  [sym_identifier] = "identifier",
  [anon_sym_POUNDNULL_BANG] = "#NULL!",
  [anon_sym_POUNDDIV_SLASH0_BANG] = "#DIV/0!",
  [anon_sym_POUNDVALUE_BANG] = "#VALUE!",
  [anon_sym_POUNDREF_BANG] = "#REF!",
  [anon_sym_POUNDNAME_QMARK] = "#NAME\?",
  [anon_sym_POUNDNUM_BANG] = "#NUM!",
  [anon_sym_POUNDN_SLASHA] = "#N/A",
  [anon_sym_POUNDERROR_BANG] = "#ERROR!",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BANG] = "!",
  [aux_sym_cell_reference_token1] = "cell_reference_token1",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_COLON] = ":",
  [sym_open_paren] = "open_paren",
  [sym_close_paren] = "close_paren",
  [sym_source_file] = "source_file",
  [sym_boolean] = "boolean",
  [sym_error_literal] = "error_literal",
  [sym_array_literal] = "array_literal",
  [sym_cell_reference] = "cell_reference",
  [sym_operator_expression] = "operator_expression",
  [sym_unary_operator] = "unary_operator",
  [sym_binary_operator] = "binary_operator",
  [sym_expression] = "expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_function_call] = "function_call",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
  [aux_sym_array_literal_repeat2] = "array_literal_repeat2",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_TRUE] = anon_sym_TRUE,
  [anon_sym_FALSE] = anon_sym_FALSE,
  [sym_identifier] = sym_identifier,
  [anon_sym_POUNDNULL_BANG] = anon_sym_POUNDNULL_BANG,
  [anon_sym_POUNDDIV_SLASH0_BANG] = anon_sym_POUNDDIV_SLASH0_BANG,
  [anon_sym_POUNDVALUE_BANG] = anon_sym_POUNDVALUE_BANG,
  [anon_sym_POUNDREF_BANG] = anon_sym_POUNDREF_BANG,
  [anon_sym_POUNDNAME_QMARK] = anon_sym_POUNDNAME_QMARK,
  [anon_sym_POUNDNUM_BANG] = anon_sym_POUNDNUM_BANG,
  [anon_sym_POUNDN_SLASHA] = anon_sym_POUNDN_SLASHA,
  [anon_sym_POUNDERROR_BANG] = anon_sym_POUNDERROR_BANG,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_cell_reference_token1] = aux_sym_cell_reference_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_open_paren] = sym_open_paren,
  [sym_close_paren] = sym_close_paren,
  [sym_source_file] = sym_source_file,
  [sym_boolean] = sym_boolean,
  [sym_error_literal] = sym_error_literal,
  [sym_array_literal] = sym_array_literal,
  [sym_cell_reference] = sym_cell_reference,
  [sym_operator_expression] = sym_operator_expression,
  [sym_unary_operator] = sym_unary_operator,
  [sym_binary_operator] = sym_binary_operator,
  [sym_expression] = sym_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_function_call] = sym_function_call,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
  [aux_sym_array_literal_repeat2] = aux_sym_array_literal_repeat2,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TRUE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FALSE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDNULL_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDDIV_SLASH0_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDVALUE_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDREF_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDNAME_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDNUM_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDN_SLASHA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDERROR_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cell_reference_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_open_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_close_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_error_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_cell_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '!', 75,
        '"', 7,
        '#', 14,
        '%', 83,
        '&', 89,
        '(', 95,
        ')', 96,
        '*', 86,
        '+', 84,
        ',', 72,
        '-', 85,
        '/', 87,
        ':', 94,
        ';', 73,
        '<', 91,
        '=', 39,
        '>', 90,
        'F', 46,
        'T', 50,
        '^', 88,
        '{', 71,
        '}', 74,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(54);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(68);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(64);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(70);
      END_STATE();
    case 6:
      if (lookahead == '!') ADVANCE(65);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(13);
      if (lookahead == 'A') ADVANCE(23);
      if (lookahead == 'U') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == '0') ADVANCE(4);
      END_STATE();
    case 11:
      if (lookahead == '?') ADVANCE(67);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(69);
      END_STATE();
    case 14:
      if (lookahead == 'D') ADVANCE(19);
      if (lookahead == 'E') ADVANCE(26);
      if (lookahead == 'N') ADVANCE(9);
      if (lookahead == 'R') ADVANCE(15);
      if (lookahead == 'V') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(6);
      END_STATE();
    case 18:
      if (lookahead == 'F') ADVANCE(2);
      END_STATE();
    case 19:
      if (lookahead == 'I') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'L') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'L') ADVANCE(22);
      if (lookahead == 'M') ADVANCE(1);
      END_STATE();
    case 22:
      if (lookahead == 'L') ADVANCE(3);
      END_STATE();
    case 23:
      if (lookahead == 'M') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'R') ADVANCE(25);
      END_STATE();
    case 27:
      if (lookahead == 'R') ADVANCE(5);
      END_STATE();
    case 28:
      if (lookahead == 'U') ADVANCE(17);
      END_STATE();
    case 29:
      if (lookahead == 'V') ADVANCE(8);
      END_STATE();
    case 30:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 31:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(35);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(36);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(34);
      END_STATE();
    case 37:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_TRUE);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_FALSE);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(56);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'U') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(56);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(56);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_POUNDNULL_BANG);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_POUNDDIV_SLASH0_BANG);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_POUNDVALUE_BANG);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POUNDREF_BANG);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUNDNAME_QMARK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_POUNDNUM_BANG);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_POUNDN_SLASHA);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_POUNDERROR_BANG);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_cell_reference_token1);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_cell_reference_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_cell_reference_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_cell_reference_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_cell_reference_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_cell_reference_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_cell_reference_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(93);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_open_paren);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_close_paren);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 31},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_TRUE] = ACTIONS(1),
    [anon_sym_FALSE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(1),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(1),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(1),
    [anon_sym_POUNDREF_BANG] = ACTIONS(1),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(1),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(1),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(1),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [aux_sym_cell_reference_token1] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_open_paren] = ACTIONS(1),
    [sym_close_paren] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [anon_sym_EQ] = ACTIONS(3),
  },
  [STATE(2)] = {
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [anon_sym_TRUE] = ACTIONS(7),
    [anon_sym_FALSE] = ACTIONS(7),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(5),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(5),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(5),
    [anon_sym_POUNDREF_BANG] = ACTIONS(5),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(5),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(5),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(5),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_COMMA] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(5),
    [anon_sym_BANG] = ACTIONS(9),
    [aux_sym_cell_reference_token1] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(11),
    [sym_close_paren] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym_binary_operator] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [anon_sym_TRUE] = ACTIONS(15),
    [anon_sym_FALSE] = ACTIONS(15),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(13),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(13),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(13),
    [anon_sym_POUNDREF_BANG] = ACTIONS(13),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(13),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(13),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(13),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(13),
    [aux_sym_cell_reference_token1] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_CARET] = ACTIONS(13),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [sym_open_paren] = ACTIONS(13),
    [sym_close_paren] = ACTIONS(13),
  },
  [STATE(4)] = {
    [sym_binary_operator] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_EQ] = ACTIONS(17),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_TRUE] = ACTIONS(19),
    [anon_sym_FALSE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(17),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(17),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(17),
    [anon_sym_POUNDREF_BANG] = ACTIONS(17),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(17),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(17),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(17),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(17),
    [aux_sym_cell_reference_token1] = ACTIONS(19),
    [anon_sym_PERCENT] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_COLON] = ACTIONS(17),
    [sym_open_paren] = ACTIONS(17),
    [sym_close_paren] = ACTIONS(17),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_TRUE] = ACTIONS(23),
    [anon_sym_FALSE] = ACTIONS(23),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(21),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(21),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(21),
    [anon_sym_POUNDREF_BANG] = ACTIONS(21),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(21),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(21),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(21),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [aux_sym_cell_reference_token1] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(21),
    [sym_open_paren] = ACTIONS(21),
    [sym_close_paren] = ACTIONS(21),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_EQ] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [sym_string] = ACTIONS(25),
    [anon_sym_TRUE] = ACTIONS(27),
    [anon_sym_FALSE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(25),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(25),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(25),
    [anon_sym_POUNDREF_BANG] = ACTIONS(25),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(25),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(25),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(25),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(25),
    [aux_sym_cell_reference_token1] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_CARET] = ACTIONS(25),
    [anon_sym_AMP] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_COLON] = ACTIONS(25),
    [sym_open_paren] = ACTIONS(25),
    [sym_close_paren] = ACTIONS(25),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [sym_number] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [anon_sym_TRUE] = ACTIONS(31),
    [anon_sym_FALSE] = ACTIONS(31),
    [sym_identifier] = ACTIONS(31),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(29),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(29),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(29),
    [anon_sym_POUNDREF_BANG] = ACTIONS(29),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(29),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(29),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(29),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(29),
    [aux_sym_cell_reference_token1] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_CARET] = ACTIONS(29),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(31),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_COLON] = ACTIONS(29),
    [sym_open_paren] = ACTIONS(29),
    [sym_close_paren] = ACTIONS(29),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_EQ] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_string] = ACTIONS(33),
    [anon_sym_TRUE] = ACTIONS(35),
    [anon_sym_FALSE] = ACTIONS(35),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(33),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(33),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(33),
    [anon_sym_POUNDREF_BANG] = ACTIONS(33),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(33),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(33),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(33),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [aux_sym_cell_reference_token1] = ACTIONS(35),
    [anon_sym_PERCENT] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(33),
    [anon_sym_AMP] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_COLON] = ACTIONS(33),
    [sym_open_paren] = ACTIONS(33),
    [sym_close_paren] = ACTIONS(33),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_EQ] = ACTIONS(37),
    [sym_number] = ACTIONS(37),
    [sym_string] = ACTIONS(37),
    [anon_sym_TRUE] = ACTIONS(39),
    [anon_sym_FALSE] = ACTIONS(39),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(37),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(37),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(37),
    [anon_sym_POUNDREF_BANG] = ACTIONS(37),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(37),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(37),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(37),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(37),
    [anon_sym_SEMI] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(37),
    [aux_sym_cell_reference_token1] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(37),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(37),
    [anon_sym_AMP] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_COLON] = ACTIONS(37),
    [sym_open_paren] = ACTIONS(37),
    [sym_close_paren] = ACTIONS(37),
  },
  [STATE(10)] = {
    [sym_binary_operator] = STATE(27),
    [aux_sym_array_literal_repeat1] = STATE(31),
    [anon_sym_EQ] = ACTIONS(41),
    [sym_number] = ACTIONS(43),
    [sym_string] = ACTIONS(43),
    [anon_sym_TRUE] = ACTIONS(45),
    [anon_sym_FALSE] = ACTIONS(45),
    [sym_identifier] = ACTIONS(45),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(43),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(43),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(43),
    [anon_sym_POUNDREF_BANG] = ACTIONS(43),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(43),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(43),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(43),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(43),
    [aux_sym_cell_reference_token1] = ACTIONS(45),
    [anon_sym_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_CARET] = ACTIONS(41),
    [anon_sym_AMP] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(41),
    [sym_open_paren] = ACTIONS(43),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [anon_sym_TRUE] = ACTIONS(15),
    [anon_sym_FALSE] = ACTIONS(15),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(13),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(13),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(13),
    [anon_sym_POUNDREF_BANG] = ACTIONS(13),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(13),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(13),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(13),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(13),
    [aux_sym_cell_reference_token1] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_CARET] = ACTIONS(13),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LT_EQ] = ACTIONS(13),
    [anon_sym_GT_EQ] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [sym_open_paren] = ACTIONS(13),
    [sym_close_paren] = ACTIONS(13),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(55),
    [sym_number] = ACTIONS(55),
    [sym_string] = ACTIONS(55),
    [anon_sym_TRUE] = ACTIONS(57),
    [anon_sym_FALSE] = ACTIONS(57),
    [sym_identifier] = ACTIONS(57),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(55),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(55),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(55),
    [anon_sym_POUNDREF_BANG] = ACTIONS(55),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(55),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(55),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(55),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(55),
    [anon_sym_COMMA] = ACTIONS(55),
    [anon_sym_SEMI] = ACTIONS(55),
    [anon_sym_RBRACE] = ACTIONS(55),
    [aux_sym_cell_reference_token1] = ACTIONS(57),
    [anon_sym_PERCENT] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(55),
    [anon_sym_SLASH] = ACTIONS(55),
    [anon_sym_CARET] = ACTIONS(55),
    [anon_sym_AMP] = ACTIONS(55),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_LT_EQ] = ACTIONS(55),
    [anon_sym_GT_EQ] = ACTIONS(55),
    [anon_sym_COLON] = ACTIONS(55),
    [sym_open_paren] = ACTIONS(55),
    [sym_close_paren] = ACTIONS(55),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(59),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [anon_sym_TRUE] = ACTIONS(61),
    [anon_sym_FALSE] = ACTIONS(61),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(59),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(59),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(59),
    [anon_sym_POUNDREF_BANG] = ACTIONS(59),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(59),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(59),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(59),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_SEMI] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(59),
    [aux_sym_cell_reference_token1] = ACTIONS(61),
    [anon_sym_PERCENT] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(59),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_CARET] = ACTIONS(59),
    [anon_sym_AMP] = ACTIONS(59),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_LT_EQ] = ACTIONS(59),
    [anon_sym_GT_EQ] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(59),
    [sym_open_paren] = ACTIONS(59),
    [sym_close_paren] = ACTIONS(59),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(63),
    [sym_number] = ACTIONS(63),
    [sym_string] = ACTIONS(63),
    [anon_sym_TRUE] = ACTIONS(65),
    [anon_sym_FALSE] = ACTIONS(65),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(63),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(63),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(63),
    [anon_sym_POUNDREF_BANG] = ACTIONS(63),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(63),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(63),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(63),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(63),
    [anon_sym_SEMI] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(63),
    [aux_sym_cell_reference_token1] = ACTIONS(65),
    [anon_sym_PERCENT] = ACTIONS(63),
    [anon_sym_PLUS] = ACTIONS(63),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_STAR] = ACTIONS(63),
    [anon_sym_SLASH] = ACTIONS(63),
    [anon_sym_CARET] = ACTIONS(63),
    [anon_sym_AMP] = ACTIONS(63),
    [anon_sym_GT] = ACTIONS(65),
    [anon_sym_LT] = ACTIONS(65),
    [anon_sym_LT_EQ] = ACTIONS(63),
    [anon_sym_GT_EQ] = ACTIONS(63),
    [anon_sym_COLON] = ACTIONS(63),
    [sym_open_paren] = ACTIONS(63),
    [sym_close_paren] = ACTIONS(63),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [anon_sym_TRUE] = ACTIONS(7),
    [anon_sym_FALSE] = ACTIONS(7),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(5),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(5),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(5),
    [anon_sym_POUNDREF_BANG] = ACTIONS(5),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(5),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(5),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(5),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_COMMA] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(5),
    [aux_sym_cell_reference_token1] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [sym_open_paren] = ACTIONS(5),
    [sym_close_paren] = ACTIONS(5),
  },
  [STATE(16)] = {
    [sym_binary_operator] = STATE(27),
    [anon_sym_EQ] = ACTIONS(41),
    [sym_number] = ACTIONS(67),
    [sym_string] = ACTIONS(67),
    [anon_sym_TRUE] = ACTIONS(69),
    [anon_sym_FALSE] = ACTIONS(69),
    [sym_identifier] = ACTIONS(69),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(67),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(67),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(67),
    [anon_sym_POUNDREF_BANG] = ACTIONS(67),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(67),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(67),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(67),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(67),
    [anon_sym_COMMA] = ACTIONS(67),
    [anon_sym_SEMI] = ACTIONS(67),
    [anon_sym_RBRACE] = ACTIONS(67),
    [aux_sym_cell_reference_token1] = ACTIONS(69),
    [anon_sym_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_CARET] = ACTIONS(41),
    [anon_sym_AMP] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(41),
    [sym_open_paren] = ACTIONS(67),
  },
  [STATE(17)] = {
    [sym_binary_operator] = STATE(27),
    [anon_sym_EQ] = ACTIONS(41),
    [sym_number] = ACTIONS(71),
    [sym_string] = ACTIONS(71),
    [anon_sym_TRUE] = ACTIONS(73),
    [anon_sym_FALSE] = ACTIONS(73),
    [sym_identifier] = ACTIONS(73),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(71),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(71),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(71),
    [anon_sym_POUNDREF_BANG] = ACTIONS(71),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(71),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(71),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(71),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(71),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_COMMA] = ACTIONS(75),
    [aux_sym_cell_reference_token1] = ACTIONS(73),
    [anon_sym_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_CARET] = ACTIONS(41),
    [anon_sym_AMP] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(41),
    [sym_open_paren] = ACTIONS(71),
    [sym_close_paren] = ACTIONS(71),
  },
  [STATE(18)] = {
    [sym_binary_operator] = STATE(27),
    [anon_sym_EQ] = ACTIONS(41),
    [sym_number] = ACTIONS(77),
    [sym_string] = ACTIONS(77),
    [anon_sym_TRUE] = ACTIONS(79),
    [anon_sym_FALSE] = ACTIONS(79),
    [sym_identifier] = ACTIONS(79),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(77),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(77),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(77),
    [anon_sym_POUNDREF_BANG] = ACTIONS(77),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(77),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(77),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(77),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [aux_sym_cell_reference_token1] = ACTIONS(79),
    [anon_sym_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_CARET] = ACTIONS(41),
    [anon_sym_AMP] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(41),
    [sym_open_paren] = ACTIONS(77),
    [sym_close_paren] = ACTIONS(77),
  },
  [STATE(19)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(16),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [sym_number] = ACTIONS(81),
    [sym_string] = ACTIONS(81),
    [anon_sym_TRUE] = ACTIONS(84),
    [anon_sym_FALSE] = ACTIONS(84),
    [sym_identifier] = ACTIONS(87),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(90),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(90),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(90),
    [anon_sym_POUNDREF_BANG] = ACTIONS(90),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(90),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(90),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(90),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(90),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_COMMA] = ACTIONS(96),
    [anon_sym_SEMI] = ACTIONS(96),
    [anon_sym_RBRACE] = ACTIONS(96),
    [aux_sym_cell_reference_token1] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_DASH] = ACTIONS(101),
    [sym_open_paren] = ACTIONS(104),
  },
  [STATE(20)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(10),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [aux_sym_array_literal_repeat2] = STATE(22),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(113),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(113),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(113),
    [anon_sym_POUNDREF_BANG] = ACTIONS(113),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(113),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(113),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(113),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(115),
    [anon_sym_RBRACE] = ACTIONS(117),
    [aux_sym_cell_reference_token1] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [sym_open_paren] = ACTIONS(123),
  },
  [STATE(21)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(17),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [aux_sym_function_call_repeat1] = STATE(24),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(113),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(113),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(113),
    [anon_sym_POUNDREF_BANG] = ACTIONS(113),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(113),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(113),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(113),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(115),
    [aux_sym_cell_reference_token1] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [sym_open_paren] = ACTIONS(123),
    [sym_close_paren] = ACTIONS(125),
  },
  [STATE(22)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(10),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [aux_sym_array_literal_repeat2] = STATE(22),
    [sym_number] = ACTIONS(127),
    [sym_string] = ACTIONS(127),
    [anon_sym_TRUE] = ACTIONS(130),
    [anon_sym_FALSE] = ACTIONS(130),
    [sym_identifier] = ACTIONS(133),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(136),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(136),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(136),
    [anon_sym_POUNDREF_BANG] = ACTIONS(136),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(136),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(136),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(136),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(136),
    [anon_sym_LBRACE] = ACTIONS(139),
    [anon_sym_RBRACE] = ACTIONS(142),
    [aux_sym_cell_reference_token1] = ACTIONS(144),
    [anon_sym_PLUS] = ACTIONS(147),
    [anon_sym_DASH] = ACTIONS(147),
    [sym_open_paren] = ACTIONS(150),
  },
  [STATE(23)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(17),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [aux_sym_function_call_repeat1] = STATE(23),
    [sym_number] = ACTIONS(153),
    [sym_string] = ACTIONS(153),
    [anon_sym_TRUE] = ACTIONS(156),
    [anon_sym_FALSE] = ACTIONS(156),
    [sym_identifier] = ACTIONS(159),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(162),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(162),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(162),
    [anon_sym_POUNDREF_BANG] = ACTIONS(162),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(162),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(162),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(162),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(162),
    [anon_sym_LBRACE] = ACTIONS(165),
    [aux_sym_cell_reference_token1] = ACTIONS(168),
    [anon_sym_PLUS] = ACTIONS(171),
    [anon_sym_DASH] = ACTIONS(171),
    [sym_open_paren] = ACTIONS(174),
    [sym_close_paren] = ACTIONS(177),
  },
  [STATE(24)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(17),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [aux_sym_function_call_repeat1] = STATE(23),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(113),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(113),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(113),
    [anon_sym_POUNDREF_BANG] = ACTIONS(113),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(113),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(113),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(113),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(115),
    [aux_sym_cell_reference_token1] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [sym_open_paren] = ACTIONS(123),
    [sym_close_paren] = ACTIONS(179),
  },
  [STATE(25)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(10),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [aux_sym_array_literal_repeat2] = STATE(20),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(113),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(113),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(113),
    [anon_sym_POUNDREF_BANG] = ACTIONS(113),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(113),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(113),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(113),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(115),
    [aux_sym_cell_reference_token1] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [sym_open_paren] = ACTIONS(123),
  },
  [STATE(26)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(18),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [sym_number] = ACTIONS(153),
    [sym_string] = ACTIONS(153),
    [anon_sym_TRUE] = ACTIONS(156),
    [anon_sym_FALSE] = ACTIONS(156),
    [sym_identifier] = ACTIONS(159),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(162),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(162),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(162),
    [anon_sym_POUNDREF_BANG] = ACTIONS(162),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(162),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(162),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(162),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(162),
    [anon_sym_LBRACE] = ACTIONS(165),
    [aux_sym_cell_reference_token1] = ACTIONS(168),
    [anon_sym_PLUS] = ACTIONS(171),
    [anon_sym_DASH] = ACTIONS(171),
    [sym_open_paren] = ACTIONS(174),
    [sym_close_paren] = ACTIONS(177),
  },
  [STATE(27)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(4),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(113),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(113),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(113),
    [anon_sym_POUNDREF_BANG] = ACTIONS(113),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(113),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(113),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(113),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(115),
    [aux_sym_cell_reference_token1] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [sym_open_paren] = ACTIONS(123),
  },
  [STATE(28)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(38),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(113),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(113),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(113),
    [anon_sym_POUNDREF_BANG] = ACTIONS(113),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(113),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(113),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(113),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(115),
    [aux_sym_cell_reference_token1] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [sym_open_paren] = ACTIONS(123),
  },
  [STATE(29)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(37),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(113),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(113),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(113),
    [anon_sym_POUNDREF_BANG] = ACTIONS(113),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(113),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(113),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(113),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(115),
    [aux_sym_cell_reference_token1] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [sym_open_paren] = ACTIONS(123),
  },
  [STATE(30)] = {
    [sym_boolean] = STATE(15),
    [sym_error_literal] = STATE(15),
    [sym_array_literal] = STATE(15),
    [sym_cell_reference] = STATE(15),
    [sym_operator_expression] = STATE(15),
    [sym_unary_operator] = STATE(30),
    [sym_expression] = STATE(3),
    [sym_parenthesized_expression] = STATE(15),
    [sym_function_call] = STATE(15),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(113),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(113),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(113),
    [anon_sym_POUNDREF_BANG] = ACTIONS(113),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(113),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(113),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(113),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(115),
    [aux_sym_cell_reference_token1] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(121),
    [sym_open_paren] = ACTIONS(123),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(47), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_SEMI,
    STATE(32), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(181), 4,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_identifier,
      aux_sym_cell_reference_token1,
    ACTIONS(142), 15,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_open_paren,
  [33] = 4,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(69), 4,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_identifier,
      aux_sym_cell_reference_token1,
    ACTIONS(67), 16,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_open_paren,
  [64] = 2,
    ACTIONS(181), 4,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_identifier,
      aux_sym_cell_reference_token1,
    ACTIONS(142), 15,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_open_paren,
  [88] = 2,
    ACTIONS(190), 4,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_identifier,
      aux_sym_cell_reference_token1,
    ACTIONS(188), 15,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_open_paren,
  [112] = 2,
    ACTIONS(194), 4,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_identifier,
      aux_sym_cell_reference_token1,
    ACTIONS(192), 14,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_open_paren,
  [135] = 2,
    ACTIONS(198), 4,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_identifier,
      aux_sym_cell_reference_token1,
    ACTIONS(196), 14,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_open_paren,
  [158] = 5,
    ACTIONS(51), 1,
      anon_sym_PERCENT,
    ACTIONS(200), 1,
      sym_close_paren,
    STATE(27), 1,
      sym_binary_operator,
    ACTIONS(53), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 10,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COLON,
  [184] = 5,
    ACTIONS(51), 1,
      anon_sym_PERCENT,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym_binary_operator,
    ACTIONS(53), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 10,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COLON,
  [210] = 1,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
  [214] = 1,
    ACTIONS(206), 1,
      aux_sym_cell_reference_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(31)] = 0,
  [SMALL_STATE(32)] = 33,
  [SMALL_STATE(33)] = 64,
  [SMALL_STATE(34)] = 88,
  [SMALL_STATE(35)] = 112,
  [SMALL_STATE(36)] = 135,
  [SMALL_STATE(37)] = 158,
  [SMALL_STATE(38)] = 184,
  [SMALL_STATE(39)] = 210,
  [SMALL_STATE(40)] = 214,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error_literal, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_error_literal, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell_reference, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell_reference, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell_reference, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell_reference, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 3, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(15),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(13),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(2),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(6),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(25),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(8),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(36),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(29),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(15),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(13),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(2),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(6),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(25),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(36),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(29),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [159] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operator, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operator, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gsheets(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gsheets",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
