/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 30
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  aux_sym_cell_pattern_token1 = 2,
  anon_sym_BANG = 3,
  sym_number = 4,
  sym_string = 5,
  anon_sym_TRUE = 6,
  anon_sym_FALSE = 7,
  aux_sym_identifier_token1 = 8,
  anon_sym_POUNDNULL_BANG = 9,
  anon_sym_POUNDDIV_SLASH0_BANG = 10,
  anon_sym_POUNDVALUE_BANG = 11,
  anon_sym_POUNDREF_BANG = 12,
  anon_sym_POUNDNAME_QMARK = 13,
  anon_sym_POUNDNUM_BANG = 14,
  anon_sym_POUNDN_SLASHA = 15,
  anon_sym_POUNDERROR_BANG = 16,
  anon_sym_LBRACE = 17,
  anon_sym_COMMA = 18,
  anon_sym_SEMI = 19,
  anon_sym_RBRACE = 20,
  anon_sym_PERCENT = 21,
  anon_sym_PLUS = 22,
  anon_sym_DASH = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  anon_sym_CARET = 26,
  anon_sym_AMP = 27,
  anon_sym_GT = 28,
  anon_sym_LT = 29,
  anon_sym_LT_GT = 30,
  anon_sym_LT_EQ = 31,
  anon_sym_GT_EQ = 32,
  anon_sym_COLON = 33,
  anon_sym_LPAREN = 34,
  anon_sym_RPAREN = 35,
  sym_source_file = 36,
  sym_cell_pattern = 37,
  sym_cell_reference = 38,
  sym_boolean = 39,
  sym_identifier = 40,
  sym_error_literal = 41,
  sym_array_literal = 42,
  sym_operator_expression = 43,
  sym_unary_operator = 44,
  sym_binary_operator = 45,
  sym_expression = 46,
  sym_parenthesized_expression = 47,
  sym_function_call = 48,
  aux_sym_array_literal_repeat1 = 49,
  aux_sym_array_literal_repeat2 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [aux_sym_cell_pattern_token1] = "cell_pattern_token1",
  [anon_sym_BANG] = "!",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_TRUE] = "TRUE",
  [anon_sym_FALSE] = "FALSE",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym_POUNDNULL_BANG] = "#NULL!",
  [anon_sym_POUNDDIV_SLASH0_BANG] = "#DIV/0!",
  [anon_sym_POUNDVALUE_BANG] = "#VALUE!",
  [anon_sym_POUNDREF_BANG] = "#REF!",
  [anon_sym_POUNDNAME_QMARK] = "#NAME\?",
  [anon_sym_POUNDNUM_BANG] = "#NUM!",
  [anon_sym_POUNDN_SLASHA] = "#N/A",
  [anon_sym_POUNDERROR_BANG] = "#ERROR!",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym_cell_pattern] = "cell_pattern",
  [sym_cell_reference] = "cell_reference",
  [sym_boolean] = "boolean",
  [sym_identifier] = "identifier",
  [sym_error_literal] = "error_literal",
  [sym_array_literal] = "array_literal",
  [sym_operator_expression] = "operator_expression",
  [sym_unary_operator] = "unary_operator",
  [sym_binary_operator] = "binary_operator",
  [sym_expression] = "expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_function_call] = "function_call",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
  [aux_sym_array_literal_repeat2] = "array_literal_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_cell_pattern_token1] = aux_sym_cell_pattern_token1,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_TRUE] = anon_sym_TRUE,
  [anon_sym_FALSE] = anon_sym_FALSE,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym_POUNDNULL_BANG] = anon_sym_POUNDNULL_BANG,
  [anon_sym_POUNDDIV_SLASH0_BANG] = anon_sym_POUNDDIV_SLASH0_BANG,
  [anon_sym_POUNDVALUE_BANG] = anon_sym_POUNDVALUE_BANG,
  [anon_sym_POUNDREF_BANG] = anon_sym_POUNDREF_BANG,
  [anon_sym_POUNDNAME_QMARK] = anon_sym_POUNDNAME_QMARK,
  [anon_sym_POUNDNUM_BANG] = anon_sym_POUNDNUM_BANG,
  [anon_sym_POUNDN_SLASHA] = anon_sym_POUNDN_SLASHA,
  [anon_sym_POUNDERROR_BANG] = anon_sym_POUNDERROR_BANG,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym_cell_pattern] = sym_cell_pattern,
  [sym_cell_reference] = sym_cell_reference,
  [sym_boolean] = sym_boolean,
  [sym_identifier] = sym_identifier,
  [sym_error_literal] = sym_error_literal,
  [sym_array_literal] = sym_array_literal,
  [sym_operator_expression] = sym_operator_expression,
  [sym_unary_operator] = sym_unary_operator,
  [sym_binary_operator] = sym_binary_operator,
  [sym_expression] = sym_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_function_call] = sym_function_call,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
  [aux_sym_array_literal_repeat2] = aux_sym_array_literal_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cell_pattern_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TRUE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FALSE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUNDNULL_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDDIV_SLASH0_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDVALUE_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDREF_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDNAME_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDNUM_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDN_SLASHA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDERROR_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_cell_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_cell_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_error_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_function_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function_name] = "function_name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 21,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 30,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '!', 54,
        '"', 7,
        '#', 14,
        '%', 84,
        '&', 90,
        '(', 97,
        ')', 98,
        '*', 87,
        '+', 85,
        ',', 81,
        '-', 86,
        '/', 88,
        ':', 96,
        ';', 82,
        '<', 92,
        '=', 39,
        '>', 91,
        'F', 61,
        'T', 65,
        '^', 89,
        '{', 80,
        '}', 83,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(69);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(77);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(75);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(72);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(73);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(79);
      END_STATE();
    case 6:
      if (lookahead == '!') ADVANCE(74);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(13);
      if (lookahead == 'A') ADVANCE(23);
      if (lookahead == 'U') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == '0') ADVANCE(4);
      END_STATE();
    case 11:
      if (lookahead == '?') ADVANCE(76);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(78);
      END_STATE();
    case 14:
      if (lookahead == 'D') ADVANCE(19);
      if (lookahead == 'E') ADVANCE(26);
      if (lookahead == 'N') ADVANCE(9);
      if (lookahead == 'R') ADVANCE(15);
      if (lookahead == 'V') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(6);
      END_STATE();
    case 18:
      if (lookahead == 'F') ADVANCE(2);
      END_STATE();
    case 19:
      if (lookahead == 'I') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'L') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'L') ADVANCE(22);
      if (lookahead == 'M') ADVANCE(1);
      END_STATE();
    case 22:
      if (lookahead == 'L') ADVANCE(3);
      END_STATE();
    case 23:
      if (lookahead == 'M') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'R') ADVANCE(25);
      END_STATE();
    case 27:
      if (lookahead == 'R') ADVANCE(5);
      END_STATE();
    case 28:
      if (lookahead == 'U') ADVANCE(17);
      END_STATE();
    case 29:
      if (lookahead == 'V') ADVANCE(8);
      END_STATE();
    case 30:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 31:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(35);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(36);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(34);
      END_STATE();
    case 37:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_cell_pattern_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_TRUE);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_FALSE);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'A') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(68);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'E') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'E') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'L') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(70);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'R') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(68);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'S') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'U') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(70);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(70);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(68);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_POUNDNULL_BANG);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_POUNDDIV_SLASH0_BANG);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_POUNDVALUE_BANG);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_POUNDREF_BANG);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_POUNDNAME_QMARK);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_POUNDNUM_BANG);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_POUNDN_SLASHA);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_POUNDERROR_BANG);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(95);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(94);
      if (lookahead == '>') ADVANCE(93);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 31},
  [43] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_cell_pattern_token1] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_TRUE] = ACTIONS(1),
    [anon_sym_FALSE] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(1),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(1),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(1),
    [anon_sym_POUNDREF_BANG] = ACTIONS(1),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(1),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(1),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(1),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(43),
    [anon_sym_EQ] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_binary_operator] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(5),
    [aux_sym_cell_pattern_token1] = ACTIONS(7),
    [sym_number] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [anon_sym_TRUE] = ACTIONS(7),
    [anon_sym_FALSE] = ACTIONS(7),
    [aux_sym_identifier_token1] = ACTIONS(7),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(5),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(5),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(5),
    [anon_sym_POUNDREF_BANG] = ACTIONS(5),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(5),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(5),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(5),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_COMMA] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(5),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LT_GT] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(5),
  },
  [STATE(3)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [aux_sym_cell_pattern_token1] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [sym_number] = ACTIONS(9),
    [sym_string] = ACTIONS(9),
    [anon_sym_TRUE] = ACTIONS(11),
    [anon_sym_FALSE] = ACTIONS(11),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(9),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(9),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(9),
    [anon_sym_POUNDREF_BANG] = ACTIONS(9),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(9),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(9),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(9),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_GT] = ACTIONS(9),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_GT_EQ] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(9),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_EQ] = ACTIONS(17),
    [aux_sym_cell_pattern_token1] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_TRUE] = ACTIONS(19),
    [anon_sym_FALSE] = ACTIONS(19),
    [aux_sym_identifier_token1] = ACTIONS(19),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(17),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(17),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(17),
    [anon_sym_POUNDREF_BANG] = ACTIONS(17),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(17),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(17),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(17),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(17),
    [anon_sym_PERCENT] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_GT] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(17),
  },
  [STATE(5)] = {
    [sym_binary_operator] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [aux_sym_cell_pattern_token1] = ACTIONS(23),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_TRUE] = ACTIONS(23),
    [anon_sym_FALSE] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(23),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(21),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(21),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(21),
    [anon_sym_POUNDREF_BANG] = ACTIONS(21),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(21),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(21),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(21),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_LT_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_EQ] = ACTIONS(25),
    [aux_sym_cell_pattern_token1] = ACTIONS(27),
    [sym_number] = ACTIONS(25),
    [sym_string] = ACTIONS(25),
    [anon_sym_TRUE] = ACTIONS(27),
    [anon_sym_FALSE] = ACTIONS(27),
    [aux_sym_identifier_token1] = ACTIONS(27),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(25),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(25),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(25),
    [anon_sym_POUNDREF_BANG] = ACTIONS(25),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(25),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(25),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(25),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_CARET] = ACTIONS(25),
    [anon_sym_AMP] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_LT_GT] = ACTIONS(25),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [aux_sym_cell_pattern_token1] = ACTIONS(31),
    [sym_number] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [anon_sym_TRUE] = ACTIONS(31),
    [anon_sym_FALSE] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(31),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(29),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(29),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(29),
    [anon_sym_POUNDREF_BANG] = ACTIONS(29),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(29),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(29),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(29),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_CARET] = ACTIONS(29),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(31),
    [anon_sym_LT_GT] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_COLON] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(29),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_EQ] = ACTIONS(33),
    [aux_sym_cell_pattern_token1] = ACTIONS(35),
    [sym_number] = ACTIONS(33),
    [sym_string] = ACTIONS(33),
    [anon_sym_TRUE] = ACTIONS(35),
    [anon_sym_FALSE] = ACTIONS(35),
    [aux_sym_identifier_token1] = ACTIONS(35),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(33),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(33),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(33),
    [anon_sym_POUNDREF_BANG] = ACTIONS(33),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(33),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(33),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(33),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_PERCENT] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(33),
    [anon_sym_AMP] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_GT] = ACTIONS(33),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_COLON] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(33),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [aux_sym_cell_pattern_token1] = ACTIONS(11),
    [sym_number] = ACTIONS(9),
    [sym_string] = ACTIONS(9),
    [anon_sym_TRUE] = ACTIONS(11),
    [anon_sym_FALSE] = ACTIONS(11),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(9),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(9),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(9),
    [anon_sym_POUNDREF_BANG] = ACTIONS(9),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(9),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(9),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(9),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_GT] = ACTIONS(9),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_GT_EQ] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(9),
  },
  [STATE(10)] = {
    [sym_binary_operator] = STATE(28),
    [aux_sym_array_literal_repeat1] = STATE(31),
    [anon_sym_EQ] = ACTIONS(37),
    [aux_sym_cell_pattern_token1] = ACTIONS(39),
    [sym_number] = ACTIONS(41),
    [sym_string] = ACTIONS(41),
    [anon_sym_TRUE] = ACTIONS(39),
    [anon_sym_FALSE] = ACTIONS(39),
    [aux_sym_identifier_token1] = ACTIONS(39),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(41),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(41),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(41),
    [anon_sym_POUNDREF_BANG] = ACTIONS(41),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(41),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(41),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(41),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(41),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(41),
    [anon_sym_PERCENT] = ACTIONS(47),
    [anon_sym_PLUS] = ACTIONS(37),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(37),
    [anon_sym_AMP] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(49),
    [anon_sym_LT_GT] = ACTIONS(37),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_COLON] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(41),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [anon_sym_EQ] = ACTIONS(51),
    [aux_sym_cell_pattern_token1] = ACTIONS(53),
    [sym_number] = ACTIONS(51),
    [sym_string] = ACTIONS(51),
    [anon_sym_TRUE] = ACTIONS(53),
    [anon_sym_FALSE] = ACTIONS(53),
    [aux_sym_identifier_token1] = ACTIONS(53),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(51),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(51),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(51),
    [anon_sym_POUNDREF_BANG] = ACTIONS(51),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(51),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(51),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(51),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(51),
    [anon_sym_LBRACE] = ACTIONS(51),
    [anon_sym_COMMA] = ACTIONS(51),
    [anon_sym_SEMI] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(51),
    [anon_sym_DASH] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(51),
    [anon_sym_SLASH] = ACTIONS(51),
    [anon_sym_CARET] = ACTIONS(51),
    [anon_sym_AMP] = ACTIONS(51),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_LT_GT] = ACTIONS(51),
    [anon_sym_LT_EQ] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(51),
    [anon_sym_COLON] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_RPAREN] = ACTIONS(51),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [aux_sym_cell_pattern_token1] = ACTIONS(23),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_TRUE] = ACTIONS(23),
    [anon_sym_FALSE] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(23),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(21),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(21),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(21),
    [anon_sym_POUNDREF_BANG] = ACTIONS(21),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(21),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(21),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(21),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_LT_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(55),
    [aux_sym_cell_pattern_token1] = ACTIONS(57),
    [sym_number] = ACTIONS(55),
    [sym_string] = ACTIONS(55),
    [anon_sym_TRUE] = ACTIONS(57),
    [anon_sym_FALSE] = ACTIONS(57),
    [aux_sym_identifier_token1] = ACTIONS(57),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(55),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(55),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(55),
    [anon_sym_POUNDREF_BANG] = ACTIONS(55),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(55),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(55),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(55),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(55),
    [anon_sym_COMMA] = ACTIONS(55),
    [anon_sym_SEMI] = ACTIONS(55),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_PERCENT] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(55),
    [anon_sym_SLASH] = ACTIONS(55),
    [anon_sym_CARET] = ACTIONS(55),
    [anon_sym_AMP] = ACTIONS(55),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_LT_GT] = ACTIONS(55),
    [anon_sym_LT_EQ] = ACTIONS(55),
    [anon_sym_GT_EQ] = ACTIONS(55),
    [anon_sym_COLON] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(55),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(59),
    [aux_sym_cell_pattern_token1] = ACTIONS(61),
    [sym_number] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [anon_sym_TRUE] = ACTIONS(61),
    [anon_sym_FALSE] = ACTIONS(61),
    [aux_sym_identifier_token1] = ACTIONS(61),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(59),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(59),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(59),
    [anon_sym_POUNDREF_BANG] = ACTIONS(59),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(59),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(59),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(59),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_SEMI] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_PERCENT] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(59),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_CARET] = ACTIONS(59),
    [anon_sym_AMP] = ACTIONS(59),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_LT_GT] = ACTIONS(59),
    [anon_sym_LT_EQ] = ACTIONS(59),
    [anon_sym_GT_EQ] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_RPAREN] = ACTIONS(59),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(63),
    [aux_sym_cell_pattern_token1] = ACTIONS(65),
    [sym_number] = ACTIONS(63),
    [sym_string] = ACTIONS(63),
    [anon_sym_TRUE] = ACTIONS(65),
    [anon_sym_FALSE] = ACTIONS(65),
    [aux_sym_identifier_token1] = ACTIONS(65),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(63),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(63),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(63),
    [anon_sym_POUNDREF_BANG] = ACTIONS(63),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(63),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(63),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(63),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(63),
    [anon_sym_SEMI] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_PERCENT] = ACTIONS(63),
    [anon_sym_PLUS] = ACTIONS(63),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_STAR] = ACTIONS(63),
    [anon_sym_SLASH] = ACTIONS(63),
    [anon_sym_CARET] = ACTIONS(63),
    [anon_sym_AMP] = ACTIONS(63),
    [anon_sym_GT] = ACTIONS(65),
    [anon_sym_LT] = ACTIONS(65),
    [anon_sym_LT_GT] = ACTIONS(63),
    [anon_sym_LT_EQ] = ACTIONS(63),
    [anon_sym_GT_EQ] = ACTIONS(63),
    [anon_sym_COLON] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_RPAREN] = ACTIONS(63),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_EQ] = ACTIONS(67),
    [aux_sym_cell_pattern_token1] = ACTIONS(69),
    [sym_number] = ACTIONS(67),
    [sym_string] = ACTIONS(67),
    [anon_sym_TRUE] = ACTIONS(69),
    [anon_sym_FALSE] = ACTIONS(69),
    [aux_sym_identifier_token1] = ACTIONS(69),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(67),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(67),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(67),
    [anon_sym_POUNDREF_BANG] = ACTIONS(67),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(67),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(67),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(67),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(67),
    [anon_sym_COMMA] = ACTIONS(67),
    [anon_sym_SEMI] = ACTIONS(67),
    [anon_sym_RBRACE] = ACTIONS(67),
    [anon_sym_PERCENT] = ACTIONS(67),
    [anon_sym_PLUS] = ACTIONS(67),
    [anon_sym_DASH] = ACTIONS(67),
    [anon_sym_STAR] = ACTIONS(67),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_CARET] = ACTIONS(67),
    [anon_sym_AMP] = ACTIONS(67),
    [anon_sym_GT] = ACTIONS(69),
    [anon_sym_LT] = ACTIONS(69),
    [anon_sym_LT_GT] = ACTIONS(67),
    [anon_sym_LT_EQ] = ACTIONS(67),
    [anon_sym_GT_EQ] = ACTIONS(67),
    [anon_sym_COLON] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(67),
    [anon_sym_RPAREN] = ACTIONS(67),
  },
  [STATE(17)] = {
    [sym_binary_operator] = STATE(28),
    [anon_sym_EQ] = ACTIONS(37),
    [aux_sym_cell_pattern_token1] = ACTIONS(71),
    [sym_number] = ACTIONS(73),
    [sym_string] = ACTIONS(73),
    [anon_sym_TRUE] = ACTIONS(71),
    [anon_sym_FALSE] = ACTIONS(71),
    [aux_sym_identifier_token1] = ACTIONS(71),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(73),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(73),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(73),
    [anon_sym_POUNDREF_BANG] = ACTIONS(73),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(73),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(73),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(73),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_COMMA] = ACTIONS(73),
    [anon_sym_SEMI] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_PERCENT] = ACTIONS(47),
    [anon_sym_PLUS] = ACTIONS(37),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(37),
    [anon_sym_AMP] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(49),
    [anon_sym_LT_GT] = ACTIONS(37),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_COLON] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(75),
    [anon_sym_EQ] = ACTIONS(75),
    [aux_sym_cell_pattern_token1] = ACTIONS(77),
    [sym_number] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_TRUE] = ACTIONS(77),
    [anon_sym_FALSE] = ACTIONS(77),
    [aux_sym_identifier_token1] = ACTIONS(77),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(75),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(75),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(75),
    [anon_sym_POUNDREF_BANG] = ACTIONS(75),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(75),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(75),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(75),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(75),
    [anon_sym_COMMA] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(75),
    [anon_sym_PERCENT] = ACTIONS(75),
    [anon_sym_PLUS] = ACTIONS(75),
    [anon_sym_DASH] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(75),
    [anon_sym_SLASH] = ACTIONS(75),
    [anon_sym_CARET] = ACTIONS(75),
    [anon_sym_AMP] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(77),
    [anon_sym_LT] = ACTIONS(77),
    [anon_sym_LT_GT] = ACTIONS(75),
    [anon_sym_LT_EQ] = ACTIONS(75),
    [anon_sym_GT_EQ] = ACTIONS(75),
    [anon_sym_COLON] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(75),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [anon_sym_EQ] = ACTIONS(79),
    [aux_sym_cell_pattern_token1] = ACTIONS(81),
    [sym_number] = ACTIONS(79),
    [sym_string] = ACTIONS(79),
    [anon_sym_TRUE] = ACTIONS(81),
    [anon_sym_FALSE] = ACTIONS(81),
    [aux_sym_identifier_token1] = ACTIONS(81),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(79),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(79),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(79),
    [anon_sym_POUNDREF_BANG] = ACTIONS(79),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(79),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(79),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(79),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_SEMI] = ACTIONS(79),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_PERCENT] = ACTIONS(79),
    [anon_sym_PLUS] = ACTIONS(79),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(79),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_CARET] = ACTIONS(79),
    [anon_sym_AMP] = ACTIONS(79),
    [anon_sym_GT] = ACTIONS(81),
    [anon_sym_LT] = ACTIONS(81),
    [anon_sym_LT_GT] = ACTIONS(79),
    [anon_sym_LT_EQ] = ACTIONS(79),
    [anon_sym_GT_EQ] = ACTIONS(79),
    [anon_sym_COLON] = ACTIONS(79),
    [anon_sym_LPAREN] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
  },
  [STATE(20)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(36),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_array_literal_repeat1] = STATE(40),
    [aux_sym_cell_pattern_token1] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_TRUE] = ACTIONS(87),
    [anon_sym_FALSE] = ACTIONS(87),
    [aux_sym_identifier_token1] = ACTIONS(89),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(91),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(91),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(91),
    [anon_sym_POUNDREF_BANG] = ACTIONS(91),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(91),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(91),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(91),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_COMMA] = ACTIONS(95),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
    [anon_sym_RPAREN] = ACTIONS(101),
  },
  [STATE(21)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(17),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_cell_pattern_token1] = ACTIONS(103),
    [sym_number] = ACTIONS(106),
    [sym_string] = ACTIONS(106),
    [anon_sym_TRUE] = ACTIONS(109),
    [anon_sym_FALSE] = ACTIONS(109),
    [aux_sym_identifier_token1] = ACTIONS(112),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(115),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(115),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(115),
    [anon_sym_POUNDREF_BANG] = ACTIONS(115),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(115),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(115),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(115),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(115),
    [anon_sym_LBRACE] = ACTIONS(118),
    [anon_sym_COMMA] = ACTIONS(121),
    [anon_sym_SEMI] = ACTIONS(121),
    [anon_sym_RBRACE] = ACTIONS(121),
    [anon_sym_PLUS] = ACTIONS(123),
    [anon_sym_DASH] = ACTIONS(123),
    [anon_sym_LPAREN] = ACTIONS(126),
  },
  [STATE(22)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(10),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_array_literal_repeat2] = STATE(23),
    [aux_sym_cell_pattern_token1] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_TRUE] = ACTIONS(87),
    [anon_sym_FALSE] = ACTIONS(87),
    [aux_sym_identifier_token1] = ACTIONS(89),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(91),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(91),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(91),
    [anon_sym_POUNDREF_BANG] = ACTIONS(91),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(91),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(91),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(91),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(129),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
  },
  [STATE(23)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(10),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_array_literal_repeat2] = STATE(23),
    [aux_sym_cell_pattern_token1] = ACTIONS(131),
    [sym_number] = ACTIONS(134),
    [sym_string] = ACTIONS(134),
    [anon_sym_TRUE] = ACTIONS(137),
    [anon_sym_FALSE] = ACTIONS(137),
    [aux_sym_identifier_token1] = ACTIONS(140),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(143),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(143),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(143),
    [anon_sym_POUNDREF_BANG] = ACTIONS(143),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(143),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(143),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(143),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(143),
    [anon_sym_LBRACE] = ACTIONS(146),
    [anon_sym_RBRACE] = ACTIONS(149),
    [anon_sym_PLUS] = ACTIONS(151),
    [anon_sym_DASH] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(154),
  },
  [STATE(24)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(17),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_cell_pattern_token1] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_TRUE] = ACTIONS(87),
    [anon_sym_FALSE] = ACTIONS(87),
    [aux_sym_identifier_token1] = ACTIONS(89),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(91),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(91),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(91),
    [anon_sym_POUNDREF_BANG] = ACTIONS(91),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(91),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(91),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(91),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_COMMA] = ACTIONS(121),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
    [anon_sym_RPAREN] = ACTIONS(121),
  },
  [STATE(25)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(10),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_array_literal_repeat2] = STATE(22),
    [aux_sym_cell_pattern_token1] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_TRUE] = ACTIONS(87),
    [anon_sym_FALSE] = ACTIONS(87),
    [aux_sym_identifier_token1] = ACTIONS(89),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(91),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(91),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(91),
    [anon_sym_POUNDREF_BANG] = ACTIONS(91),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(91),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(91),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(91),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
  },
  [STATE(26)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(5),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_cell_pattern_token1] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_TRUE] = ACTIONS(87),
    [anon_sym_FALSE] = ACTIONS(87),
    [aux_sym_identifier_token1] = ACTIONS(89),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(91),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(91),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(91),
    [anon_sym_POUNDREF_BANG] = ACTIONS(91),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(91),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(91),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(91),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
  },
  [STATE(27)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(38),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_cell_pattern_token1] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_TRUE] = ACTIONS(87),
    [anon_sym_FALSE] = ACTIONS(87),
    [aux_sym_identifier_token1] = ACTIONS(89),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(91),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(91),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(91),
    [anon_sym_POUNDREF_BANG] = ACTIONS(91),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(91),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(91),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(91),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
  },
  [STATE(28)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(2),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_cell_pattern_token1] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_TRUE] = ACTIONS(87),
    [anon_sym_FALSE] = ACTIONS(87),
    [aux_sym_identifier_token1] = ACTIONS(89),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(91),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(91),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(91),
    [anon_sym_POUNDREF_BANG] = ACTIONS(91),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(91),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(91),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(91),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
  },
  [STATE(29)] = {
    [sym_cell_pattern] = STATE(11),
    [sym_cell_reference] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(3),
    [sym_error_literal] = STATE(9),
    [sym_array_literal] = STATE(9),
    [sym_operator_expression] = STATE(9),
    [sym_unary_operator] = STATE(26),
    [sym_expression] = STATE(37),
    [sym_parenthesized_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_cell_pattern_token1] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_TRUE] = ACTIONS(87),
    [anon_sym_FALSE] = ACTIONS(87),
    [aux_sym_identifier_token1] = ACTIONS(89),
    [anon_sym_POUNDNULL_BANG] = ACTIONS(91),
    [anon_sym_POUNDDIV_SLASH0_BANG] = ACTIONS(91),
    [anon_sym_POUNDVALUE_BANG] = ACTIONS(91),
    [anon_sym_POUNDREF_BANG] = ACTIONS(91),
    [anon_sym_POUNDNAME_QMARK] = ACTIONS(91),
    [anon_sym_POUNDNUM_BANG] = ACTIONS(91),
    [anon_sym_POUNDN_SLASHA] = ACTIONS(91),
    [anon_sym_POUNDERROR_BANG] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(71), 4,
      aux_sym_cell_pattern_token1,
      anon_sym_TRUE,
      anon_sym_FALSE,
      aux_sym_identifier_token1,
    ACTIONS(73), 16,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [31] = 5,
    ACTIONS(43), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(160), 4,
      aux_sym_cell_pattern_token1,
      anon_sym_TRUE,
      anon_sym_FALSE,
      aux_sym_identifier_token1,
    ACTIONS(149), 15,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [64] = 2,
    ACTIONS(164), 4,
      aux_sym_cell_pattern_token1,
      anon_sym_TRUE,
      anon_sym_FALSE,
      aux_sym_identifier_token1,
    ACTIONS(166), 15,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [88] = 2,
    ACTIONS(160), 4,
      aux_sym_cell_pattern_token1,
      anon_sym_TRUE,
      anon_sym_FALSE,
      aux_sym_identifier_token1,
    ACTIONS(149), 15,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [112] = 2,
    ACTIONS(168), 4,
      aux_sym_cell_pattern_token1,
      anon_sym_TRUE,
      anon_sym_FALSE,
      aux_sym_identifier_token1,
    ACTIONS(170), 14,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [135] = 2,
    ACTIONS(172), 4,
      aux_sym_cell_pattern_token1,
      anon_sym_TRUE,
      anon_sym_FALSE,
      aux_sym_identifier_token1,
    ACTIONS(174), 14,
      sym_number,
      sym_string,
      anon_sym_POUNDNULL_BANG,
      anon_sym_POUNDDIV_SLASH0_BANG,
      anon_sym_POUNDVALUE_BANG,
      anon_sym_POUNDREF_BANG,
      anon_sym_POUNDNAME_QMARK,
      anon_sym_POUNDNUM_BANG,
      anon_sym_POUNDN_SLASHA,
      anon_sym_POUNDERROR_BANG,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
  [158] = 7,
    ACTIONS(47), 1,
      anon_sym_PERCENT,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_binary_operator,
    STATE(41), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(49), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(37), 11,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_AMP,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COLON,
  [191] = 5,
    ACTIONS(47), 1,
      anon_sym_PERCENT,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_binary_operator,
    ACTIONS(49), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(37), 11,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_AMP,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COLON,
  [218] = 5,
    ACTIONS(47), 1,
      anon_sym_PERCENT,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_binary_operator,
    ACTIONS(49), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(37), 11,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_AMP,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COLON,
  [245] = 3,
    ACTIONS(73), 1,
      anon_sym_RPAREN,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_array_literal_repeat1,
  [255] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_array_literal_repeat1,
  [265] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_array_literal_repeat1,
  [275] = 2,
    ACTIONS(187), 1,
      aux_sym_cell_pattern_token1,
    STATE(13), 1,
      sym_cell_pattern,
  [282] = 1,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(30)] = 0,
  [SMALL_STATE(31)] = 31,
  [SMALL_STATE(32)] = 64,
  [SMALL_STATE(33)] = 88,
  [SMALL_STATE(34)] = 112,
  [SMALL_STATE(35)] = 135,
  [SMALL_STATE(36)] = 158,
  [SMALL_STATE(37)] = 191,
  [SMALL_STATE(38)] = 218,
  [SMALL_STATE(39)] = 245,
  [SMALL_STATE(40)] = 255,
  [SMALL_STATE(41)] = 265,
  [SMALL_STATE(42)] = 275,
  [SMALL_STATE(43)] = 282,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator_expression, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell_pattern, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell_pattern, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error_literal, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_error_literal, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell_reference, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell_reference, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell_reference, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell_reference, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 1),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(6),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(9),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(7),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(4),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(8),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(25),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(34),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 1, 0, 0), SHIFT_REPEAT(27),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(6),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(9),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(7),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(25),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(34),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(27),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_literal_repeat2, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat2, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operator, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operator, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [189] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gsheets(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gsheets",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
